server:
  port: 0
spring:
  application:
    name: user-service
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enable: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#  application:
#    name: user-service
#  datasource:
#      url: jdbc:postgresql://localhost:5432/user_service_db
#      username: ${JDBC_USERNAME_LOCALHOST}
#      password: ${JDBC_PASSWORD_LOCALHOST}
#      driver-class-name: org.postgresql.Driver
#      jpa:
#        hibernate:
#          ddl-auto: update
#        properties:
#          hibernate:
#            dialect: org.hibernate.dialect.PostgreSQLDialect
#        show-sql: true
#        open-in-view: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
jwt:
  secret: aMinhaChaveSuperSecretaParaJWT32
  expiration:
    ms: 3600000

logging:
  level:
    org.springframework.security: DEBUG
    com.uelisson.UserController: DEBUG